### ISSUE TITLE
deploy機能

### ISSUE THREAD

**Issue by uchicom** [uchicom/plate#40]
# GOAL
deployする際は
```
lsdl #list downloadの略
```
を実行するとgithubからダウンロードしたディレクトリの一覧を表示する。
設定
```
github:
  hoge:
    dirPath:release
```
だったら

```
github hoge
  release
    - v20230222 latest # 作成日が一番新しい,新しい順に並べる
      - hoge.jar
      - hoge.zip
    - v20230221
      - hoge.jar
      - hoge.zip
```
`deploy service`を実行すると、latestを対象に配置場所にコピーする  
```
deploy hoge
```
`deploy service tag`を実行ると、指定のタグで配置場所にコピーする
```
deploy hoge v20230221
```
config.yml
```
deploy:
  hoge: # githubの設定名を指定
    - from: /hoge.jar # 単純移動
      to: hoge/hoge/
    - from: /hoge.tar.gz
      decompress: */www/* #アーカイブファイルを展開してフィルタリングする
      to: hoge/www/
```

# UT
junit

# IT
- [x] deployコマンド実行して確認
