### ISSUE TITLE
設定ファイルをyml形式に変更する

### ISSUE THREAD

**Issue by uchicom** [uchicom/plate#9]
# GOAL
yml形式の設定ファイルに対応する。

# DESIGN
## 設定ファイル
```
user: ユーザ名
hash: パスワードhash
service:
  classPath:
  batches:
    - key:
      classPath:
        - hoge1.jar
        - hoge2.jar
      className: com.uchicom.hoge.Main
      startMethod: main
      shutdownMethod: shutdown
      parameter:[a, b, c, d] 
      disabled: true or false サーバのON/OFF切り替え
  
      recovery: auto,manual autoの場合は自動再起動、manualは手で再起動する。 
batch:
  classPath:
  batches:
    - key:
      classPath:
        - hoge1.jar
        - hoge2.jar
      className: com.uchicom.hoge.Main
      startMethod: main
      shutdownMethod: shutdown
      parameter:[a, b, c, d] 
      disabled: true or false default false スケジュールのON/OFF切り替え
      schedule: 
        cron:[1,2,3,4,5]
        minute:
        hour:
        day:
        month:
        dayOfWeek: 未対応 スケジュールする際に
```

# UT
junit

# IT
- [x] yamlを指定して起動
